DFSL/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('password_generator.urls')),
    path('portfolio', include('portfolio.urls')),
    path('blog', include('ngite_blog.urls')),
    path('kaamkaj', include('kaamkaj.urls')),
    
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name="password-reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'registration/password_reset_done.html'),name='password_reset_done'),    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'registration/password_reset_complete.html'),name='password_reset_complete'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngite_blog/urls.py
from django.urls import path
from ngite_blog.views import *

app_name ='blog'

urlpatterns = [
    path('', my_blogs, name='all_blog'),
    path('<int:blog_id>/', blog_deatail, name='blog_detail'),
]

portfolio/urls.py
from django.urls import path
from portfolio.views import *

urlpatterns =[
    path('', portfolio, name='my_portfolio')
]

portfolio/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
	title 		= models.CharField(max_length=100)
	description = models.CharField(max_length=250)
	image 		= models.ImageField(upload_to='portfolio/images')
	url 		= models.URLField(max_length=200, blank=True)

	def __str__(self):
		return self.title

portfolio/views.py
from django.shortcuts import render
from portfolio.models import *
# Create your views here.

def portfolio(request):
	projects = Project.objects.all()
	return render(request, 'portfolio/portfolio.html',locals())

templates/portfolio/portfolio.html
{% extends './portfolio_base.html' %}

{% load static %}

{% block content %}

<div class="content">
  <div class="card">

    <div class="row justify-content-center my-3">
      <div class="col-5">
        <img src="{% static 'portfolio/couple.png' %}" class="img-fluid">
      </div>
    </div>

    <div class="row justify-content-center mb-3">
      <div class="col-md-9 text-center">
        <p  class="font-weight-bold">Jai has passed his 12th and He is from Delhi, now working as a Python developer in Mahiti Infotech, Bangalore. Interested in social welfare and intracting with new peoples. 😊</p>
      </div>
    </div>

    <h2 class="mt-5">Django Projects</h2>
    <hr>

    <div class="row">
      {% for project in projects %}
      <div class="col-lg-4 col-md-6">

        {% if project.url %}
          <a href="{{ project.url }}">
            <img src="{{ project.image.url }}" width="100%" height="200px">
          </a>
        {% else %}
          <img src="{{ project.image.url }}" width="100%" height="200px">
        {% endif %}
      
        <h3>{{ project.title }}</h3>
        <p>{{ project.description }}</p>

      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

templates/portfolio/portfolio_base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/Ngite new Logo.png" %}">

  <title>Ngite Human Code</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'welcome-page' %}">
        <img src="{% static "portfolio/Ngite new Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Jai's Logo">
        <span>Ngite Human Code</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li>
            <a class="btn btn-danger" href="{% url 'welcome-page' %}">Home</a>
          </li>
          <li>
            <a class="btn btn-success" href="{% static 'portfolio/resume.pdf' %}">Resume</a>
          </li>          
          <li >
            <a class="btn btn-info" href="#" target="_blank">LinkedIn</a>
          </li>
          <li>
            <a class="btn btn-warning" href="#" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>