DFSL/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_profile.urls')),
    path('', include('password_generator.urls')),
    path('portfolio', include('portfolio.urls')),
    path('blog', include('ngite_blog.urls')),
    path('kaamkaj', include('kaamkaj.urls')),
    
    path('password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),name="password-reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name= 'registration/password_reset_done.html'),name='password_reset_done'),    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name= 'registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'registration/password_reset_complete.html'),name='password_reset_complete'),    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ngite_blog/urls.py
from django.urls import path
from ngite_blog.views import *

app_name ='blog'

urlpatterns = [
    path('', my_blogs, name='all_blog'),
    path('<int:blog_id>/', blog_deatail, name='blog_detail'),
]

ngite_blog/models.py
from django.db import models
# Create your models here.

class Blog(models.Model):
	title 		= models.CharField(max_length=150)
	created 	= models.DateTimeField(auto_now_add=True)
	description = models.TextField()

	def __str__(self):
		return self.title

ngite_blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
# Create your views here.

def my_blogs(request):
	blogs  = Blog.objects.order_by('-created')
	return render(request, 'ngite_blog/blogs.html',locals())


def blog_deatail(request,blog_id):
	blog = get_object_or_404(Blog, pk=blog_id)
	return render(request, 'ngite_blog/details.html',locals())

templates/ngite_blog/blogs.html
{% extends 'portfolio/portfolio_base.html' %}

{% load static %}

{% block content %}
<div class="content">
	<div class="card">
		<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

		<h3 class="text-center mb-5">Jai has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>

		{% for blog in blogs %}
			<div class="row justify-content-center my-3">
			  <div class="col-md-10">
			    <a href="{% url 'blog:blog_detail' blog.id %}">
			      <h2>{{ blog.title }}</h2>
			    </a>
			    
			    <h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
			    <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
			  </div>
			</div>
		{% endfor %}
	</div>
</div>


{% endblock %}

templates/ngite_blog/details.html
{% extends 'portfolio/portfolio_base.html' %}

{% load static %}

{% block content %}

<div class="content">
	<div class="card">
		<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

		<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

		<p>{{ blog.description|safe }}</p>
		
	</div>
</div>


{% endblock %}